<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Deal\Concertable.B2B.Deal.Contracts\Concertable.B2B.Deal.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Opportunity\Concertable.B2B.Opportunity.Contracts\Concertable.B2B.Opportunity.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Venue\Concertable.B2B.Venue.Contracts\Concertable.B2B.Venue.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Concertable.Contracts" />
    <PackageReference Include="Dunet" />
    <PackageReference Include="Reunion" />
    <PackageReference Include="Reunion.Errors" />
  </ItemGroup>
</Project>
