// <auto-generated />
using System;
using Concertable.B2B.Deal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concertable.B2B.Deal.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DealDbContext))]
    [Migration("20260816155048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("deal")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DealTerms", "deal");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitTermsEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DoorSplitTerms", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeTermsEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("FlatFeeTerms", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireTermsEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VenueHireTerms", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusTermsEntity", b =>
                {
                    b.HasBaseType("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("VersusTerms", "deal");
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.DoorSplitTermsEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.DoorSplitTermsEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.FlatFeeTermsEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.FlatFeeTermsEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VenueHireTermsEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VenueHireTermsEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Deal.Domain.Entities.VersusTermsEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Deal.Domain.Entities.DealTermsEntity", null)
                        .WithOne()
                        .HasForeignKey("Concertable.B2B.Deal.Domain.Entities.VersusTermsEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
