// <auto-generated />
using System;
using System.Collections.Generic;
using Concertable.B2B.Concert.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Concertable.B2B.Concert.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ConcertDbContext))]
    [Migration("20260905134246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("concert")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concertable.B2B.Artist.Domain.ReadModels.ArtistRatingProjection", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("ArtistRatingProjections", "artist", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CancellationOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SettlementGrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SettlementOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("TicketsSold")
                        .HasColumnType("int");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FinancialFailure", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.FinancialFailure#FinancialFailure", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FinancialFailureCode");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("FinancialFailureMessage");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.Period#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("End")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SettlementPaymentReference", "Concertable.B2B.Concert.Domain.Entities.ConcertEntity.SettlementPaymentReference#PaymentOperationReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClientReference")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("OperationType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CancellationOperationId")
                        .IsUnique()
                        .HasFilter("[CancellationOperationId] IS NOT NULL");

                    b.HasIndex("SettlementOperationId")
                        .IsUnique()
                        .HasFilter("[SettlementOperationId] IS NOT NULL");

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts", "concert");

                    b.HasDiscriminator<int>("DealType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcertId");

                    b.ToTable("ConcertImages", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.InvoiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ArtistTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealType")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PdfBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TaxPointUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("VenueTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amounts", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Amounts#VatBreakdown", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Gross")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Net")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Rate")
                                .HasPrecision(5, 4)
                                .HasColumnType("decimal(5,4)");

                            b1.Property<decimal>("Vat")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Customer", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Customer#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Supplier", "Concertable.B2B.Concert.Domain.Entities.InvoiceEntity.Supplier#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("TenantId");

                    b.ToTable("InvoiceSequences", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClauseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformTermsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Supplier", "Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity.Supplier#InvoiceParty", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AddressLine1")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("AddressLine2")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("VatNumber")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SupplierESignature", "Concertable.B2B.Concert.Domain.Entities.SelfBillingAgreementEntity.SupplierESignature#ESignature", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("AtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DrawnSignatureImage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ip")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)");

                            b1.Property<string>("SignatoryName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");
                        });

                    b.HasKey("Id");

                    b.ToTable("SelfBillingAgreements", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("ArtistReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.Property<int>("ArtistReadModelId")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.HasKey("ArtistReadModelId", "Genre");

                    b.ToTable("ArtistReadModelGenres", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ConcertRatingProjection", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.ToTable("ConcertRatingProjections", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("VenueReadModels", "concert");
                });

            modelBuilder.Entity("Concertable.B2B.Venue.Domain.ReadModels.VenueRatingProjection", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("VenueId");

                    b.ToTable("VenueRatingProjections", "venue", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.DoorSplitConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DoorRevenue")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.FlatFeeConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.VenueHireConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("HireFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.VersusConcert", b =>
                {
                    b.HasBaseType("Concertable.B2B.Concert.Domain.Entities.ConcertEntity");

                    b.Property<decimal>("ArtistDoorPercent")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DoorRevenue")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Guarantee")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertImageEntity", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", "Concert")
                        .WithMany("Images")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ArtistReadModelId")
                                .HasColumnType("int");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Town");

                            b1.HasKey("ArtistReadModelId");

                            b1.ToTable("ArtistReadModels", "concert");

                            b1.WithOwner()
                                .HasForeignKey("ArtistReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.HasOne("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", "Artist")
                        .WithMany("Genres")
                        .HasForeignKey("ArtistReadModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("VenueReadModelId")
                                .HasColumnType("int");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Town");

                            b1.HasKey("VenueReadModelId");

                            b1.ToTable("VenueReadModels", "concert");

                            b1.WithOwner()
                                .HasForeignKey("VenueReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.Entities.ConcertEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Concertable.B2B.Concert.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Navigation("Genres");
                });
#pragma warning restore 612, 618
        }
    }
}
